import type { editor } from 'monaco-editor'

export const themeName = 'aurora'

export const themeData: editor.IStandaloneThemeData = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: 'comment', foreground: '4B5563', fontStyle: 'italic' },
    { token: 'string', foreground: '34D399' },
    { token: 'keyword', foreground: 'A78BFA', fontStyle: 'bold' },
    { token: 'number', foreground: 'FBBF24' },
    { token: 'type', foreground: 'C4B5FD' },
    { token: 'class.name', foreground: 'C4B5FD' },
    { token: 'function', foreground: '6EE7B7' },
    { token: 'variable', foreground: 'D1FAE5' },
    { token: 'operator', foreground: '8B5CF6' },
    { token: 'constant', foreground: 'FBBF24' },
    { token: 'tag', foreground: 'A78BFA' },
    { token: 'attribute.name', foreground: '6EE7B7' },
    { token: 'punctuation', foreground: '9CA3AF' },
    { token: 'regexp', foreground: 'F472B6' },
  ],
  colors: {
    'editor.background': '#0A0F0D',
    'editor.foreground': '#D1FAE5',
    'editor.lineHighlightBackground': '#111815',
    'editor.selectionBackground': '#10B98140',
    'editorCursor.foreground': '#10B981',
    'editorLineNumber.foreground': '#374151',
    'editorLineNumber.activeForeground': '#9CA3AF',
    'editorIndentGuide.background': '#1F2937',
    'editorIndentGuide.activeBackground': '#374151',
    'editorBracketMatch.background': '#10B98130',
    'editorBracketMatch.border': '#10B981',
    'editor.findMatchBackground': '#34D39940',
    'editor.findMatchHighlightBackground': '#34D39920',
    'editorWidget.background': '#111827',
    'editorWidget.border': '#1F2937',
    'editorSuggestWidget.background': '#1F2937',
    'editorSuggestWidget.border': '#374151',
    'editorSuggestWidget.selectedBackground': '#10B98140',
    'scrollbarSlider.background': '#37415180',
    'scrollbarSlider.hoverBackground': '#4B5563',
    'scrollbarSlider.activeBackground': '#10B98180',
    'editorOverviewRuler.border': '#00000000',
    'minimap.background': '#0A0F0D',
  },
}
