import type { editor } from 'monaco-editor'

export const themeName = 'ember'

export const themeData: editor.IStandaloneThemeData = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: 'comment', foreground: '6B7280', fontStyle: 'italic' },
    { token: 'string', foreground: 'FB923C' },
    { token: 'keyword', foreground: 'EF4444', fontStyle: 'bold' },
    { token: 'number', foreground: 'FBBF24' },
    { token: 'type', foreground: 'FB7185' },
    { token: 'class.name', foreground: 'FB7185' },
    { token: 'function', foreground: 'F97316' },
    { token: 'variable', foreground: 'FDE8E8' },
    { token: 'operator', foreground: 'F43F5E' },
    { token: 'constant', foreground: 'FBBF24' },
    { token: 'tag', foreground: 'EF4444' },
    { token: 'attribute.name', foreground: 'F97316' },
    { token: 'punctuation', foreground: 'D1D5DB' },
    { token: 'regexp', foreground: 'C084FC' },
  ],
  colors: {
    'editor.background': '#120A0A',
    'editor.foreground': '#FDE8E8',
    'editor.lineHighlightBackground': '#2A1111',
    'editor.selectionBackground': '#EF444440',
    'editorCursor.foreground': '#EF4444',
    'editorLineNumber.foreground': '#4B5563',
    'editorLineNumber.activeForeground': '#D1D5DB',
    'editorIndentGuide.background': '#3F1D1D',
    'editorIndentGuide.activeBackground': '#7F1D1D',
    'editorBracketMatch.background': '#EF444430',
    'editorBracketMatch.border': '#EF4444',
    'editor.findMatchBackground': '#F9731640',
    'editor.findMatchHighlightBackground': '#F9731620',
    'editorWidget.background': '#1A0F0F',
    'editorWidget.border': '#3F1D1D',
    'editorSuggestWidget.background': '#2A1111',
    'editorSuggestWidget.border': '#3F1D1D',
    'editorSuggestWidget.selectedBackground': '#EF444440',
    'scrollbarSlider.background': '#3F1D1D80',
    'scrollbarSlider.hoverBackground': '#7F1D1D',
    'scrollbarSlider.activeBackground': '#EF444480',
    'editorOverviewRuler.border': '#00000000',
    'minimap.background': '#120A0A',
  },
}
