import type { editor } from 'monaco-editor'

export const themeName = 'midnight'

export const themeData: editor.IStandaloneThemeData = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: 'comment', foreground: '6B7280', fontStyle: 'italic' },
    { token: 'string', foreground: '06B6D4' },
    { token: 'keyword', foreground: '8B5CF6', fontStyle: 'bold' },
    { token: 'number', foreground: 'F59E0B' },
    { token: 'type', foreground: 'C084FC' },
    { token: 'class.name', foreground: 'C084FC' },
    { token: 'function', foreground: '22D3EE' },
    { token: 'variable', foreground: 'E4E4E7' },
    { token: 'operator', foreground: 'A78BFA' },
    { token: 'constant', foreground: 'F59E0B' },
    { token: 'tag', foreground: '8B5CF6' },
    { token: 'attribute.name', foreground: '22D3EE' },
    { token: 'punctuation', foreground: 'A1A1AA' },
    { token: 'regexp', foreground: 'F43F5E' },
  ],
  colors: {
    'editor.background': '#0D0D12',
    'editor.foreground': '#E4E4E7',
    'editor.lineHighlightBackground': '#1A1A2E',
    'editor.selectionBackground': '#8B5CF640',
    'editorCursor.foreground': '#8B5CF6',
    'editorLineNumber.foreground': '#4B5563',
    'editorLineNumber.activeForeground': '#A1A1AA',
    'editorIndentGuide.background': '#2A2A3A',
    'editorIndentGuide.activeBackground': '#3F3F5A',
    'editorBracketMatch.background': '#8B5CF630',
    'editorBracketMatch.border': '#8B5CF6',
    'editor.findMatchBackground': '#06B6D440',
    'editor.findMatchHighlightBackground': '#06B6D420',
    'editorWidget.background': '#111118',
    'editorWidget.border': '#2A2A3A',
    'editorSuggestWidget.background': '#16161E',
    'editorSuggestWidget.border': '#2A2A3A',
    'editorSuggestWidget.foreground': '#E4E4E7',
    'editorSuggestWidget.selectedBackground': '#8B5CF640',
    'editorSuggestWidget.selectedForeground': '#FFFFFF',
    'editorSuggestWidget.highlightForeground': '#8B5CF6',
    'editorSuggestWidget.focusHighlightForeground': '#06B6D4',
    'scrollbarSlider.background': '#2A2A3A80',
    'scrollbarSlider.hoverBackground': '#3F3F5A',
    'scrollbarSlider.activeBackground': '#8B5CF680',
    'editorOverviewRuler.border': '#00000000',
    'minimap.background': '#0D0D12',
  },
}
